name: Combined CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  cypress_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Start Server
        run: |
          npm run start-prod &
          echo "Server started in the background"
      - name: Run Cypress E2E Tests (Headless)
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e:headless
          wait-on: http://localhost:5000
          wait-on-timeout: 10

  directory_content_job:
    runs-on: ubuntu-20.04
    needs: cypress_job
    steps:
      - name: Directory content
        run: ls -l

  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    needs: directory_content_job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run test
        run: npm run test

  hello_world_job:
    runs-on: ubuntu-20.04
    needs: simple_deployment_pipeline
    steps:
      - name: Say hello
        run: echo "Hello World! Hola mundo"

  date_job:
    runs-on: ubuntu-20.04
    needs: hello_world_job
    steps:
      - name: Now it is
        run: date -u
