name: Periodic Health Check

on:
  schedule:
    - cron: '* * * * *'
  push:

jobs:
  health-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed apps URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: 'https://aigar-pokedex.fly.dev/health'

      - name: Notify success on Discord
        if: success()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          description: '## Periodic health check succeeded'
          details: 'https://aigar-pokedex.fly.dev is up and running'

  failure_notification:
    if: failure()
    needs: [health-check]
    runs-on: ubuntu-20.04
    steps:
      - name: Notify failed health-check in discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error          
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          description: '## Periodic health check failed'
          details: 'https://aigar-pokedex.fly.dev is having some issues'