name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Get current date
        id: date
        run: 
            echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV     
      - name: Print current date
        id: print_date
        run: 
            echo $NOW  
      - name: List files
        id: list_files
        run: 
            ls -la         
      - name: List files in working directory
        id: print_tree
        working-directory: ${{ github.workspace }} 
        run: 
            tree                              