name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World! Hola mundo"
  date_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Now it is
        run: |
          date -u
  directory_content_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Directory content
        run: |
          ls -l
  cypress_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Start Server
        run: |
          npm run start-prod &
          echo "Server started in the background"

      - name: Run Cypress E2E Tests (Headless)
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e:headless
          start: npm run start-prod
          wait-on: http://localhost:5000
          wait-on-timeout: 60 # optional: adjust timeout as needed