name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Deploy app
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Notify success on Discord
        if: success()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: Tonk Badonkadonk
          color: '#ff00aa'
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: >
            Author: ${{ github.actor }} \n
            Repository: ${{ github.repository }}
          details: >
            Message: ${{ github.event.head_commit.message }} \n
            Branch: ${{ github.ref }}
          footer: Friday deployments are the best
          text: A new version of pokedex successfully deployed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  failure_notification:
    if: failure()
    needs: [simple_deployment_pipeline, tag_release]
    runs-on: ubuntu-20.04
    steps:
      - name: Notify failure on Discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          username: Tonk Badonkadonk
          color: '#ff0000'
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: >
            Build or deployment failed! \n
            Blame this guy: ${{ github.actor }} \n
            Repository: ${{ github.repository }}
          details: >
            Failure details: \n
            Commit SHA: ${{ github.sha }} \n
            Commit Message: ${{ github.event.head_commit.message }} \n
            Branch: ${{ github.ref }}
          footer: Friday deployments are the best
          text: EPIC FAIL
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}